server:
  port: ${SERVER_PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: ${URI}
          clone-on-start: ${CLONE_ON_START:true}
          default-label: ${DEFAULT_LABEL:main}
